name: cq
channels:
  - conda-forge
dependencies:
  - python=3.13
  - cadquery=2.7
  - jupyterlab=4.4
  - matplotlib=3.10
  - build123d
  - pip
  - pip:
    - jupyter-cadquery==4.0.2
    - ocp-vscode==2.7.1
    - pyvista==0.47.3
    - opencv-python==4.13.0.92
    - pytest==9.0.3
    - halo
    - html_sanitizer
    - pytest-xdist
    - pydantic-changedetect
    - pydantic-settings      # Added back for Pydantic v2 settings support
    - pytest-mock 
    - numpy
