name: cq
channels:
  - conda-forge
dependencies:
  - python=3.13
  - matplotlib=3.10
  - build123d
  - pybullet
  - pyyaml
  - pip
  - pip:
    - ocp-vscode==2.7.1
    - pyvista==0.47.3
    - opencv-python==4.13.0.92
    - ocp_vscode
    - pytest==9.0.3
    - halo
    - pytest-xdist
    - pydantic-changedetect
    - pydantic-settings
    - pytest-mock 
    - pytest-timeout
    - numpy
    - scipy
    - rerun-sdk
    - trimesh
    - jax
    - jaxlib
    - jax-md
    - scancode-toolkit
    - typecode-libmagic